@startuml
left to right direction

 actor Paciente

  Paciente -- (CU15_EliminarMedicacionHabitual) 

	 (CU15_EliminarMedicacionHabitual) .down--> (CU_13_VisordeMedicaciónHabitual) : require
	 (CU_13_VisordeMedicaciónHabitual) .left--> (CU14_AltaMedicacionHabitual) : require

@enduml