@startuml Package de Usuario
skinparam linetype ortho
skinparam class {
	BackgroundColor<<Entity>> LightBlue
	BorderColor<<Entity>> DarkGreen
}

package Service {

	package Usuario{
		interface UsuarioService{}
		class UsuarioServiceImpl{}

		interface UsuarioContactoService{}
		class UsuarioContactoServiceImpl{}

		interface UsuarioDireccionService{}
		class UsuarioDireccionServiceImpl{}

		interface ObraSocialService{}
		class ObraSocialServiceImpl{}

		interface GrupoService{}
		class GrupoServiceImpl{}

		interface RolService{}
		class RolServiceImpl{}

		interface PermisoService{}
		class PermisoServiceImpl{}
	}

	package Prescripcion{
		interface PrescripcionService{}
		interface RecetaService{}
		interface EstudioService{}
		interface AdjuntoService{}
		class PrescripcionServiceImpl{}
		class RecetaServiceImpl{}
		class EstudioServiceImpl{}
		class AdjuntoServiceImpl{}
	}

	interface GeoUbicacionService{}
	class GeoUbicacionServiceImpl{}

	interface HistoriaMedicaService{}
	class HistoriaMedicaServiceImpl{}

	interface VisitaMedicaService{}
	class VisitaMedicaServiceImpl

	UsuarioService <|.. UsuarioServiceImpl
	UsuarioServiceImpl o-right- UsuarioDireccionService
	UsuarioServiceImpl o-left- UsuarioContactoService
	UsuarioServiceImpl o-- ObraSocialService
	UsuarioServiceImpl o-- GrupoService
	UsuarioServiceImpl o-- RolService
	UsuarioServiceImpl o-- PermisoService

	UsuarioContactoService <|.. UsuarioContactoServiceImpl
	UsuarioDireccionService <|.. UsuarioDireccionServiceImpl
	ObraSocialService <|.. ObraSocialServiceImpl

	PermisoService <|.. PermisoServiceImpl
	RolService <|.. RolServiceImpl
	GrupoService <|.. GrupoServiceImpl

	GrupoServiceImpl o-- RolService
	GrupoServiceImpl o-- PermisoService

	PrescripcionService <|.. PrescripcionServiceImpl

	RecetaService <|.. RecetaServiceImpl
	EstudioService <|.. EstudioServiceImpl
	AdjuntoService <|.. AdjuntoServiceImpl

	PrescripcionServiceImpl o-left- EstudioService
	PrescripcionServiceImpl o-right- RecetaService

	EstudioServiceImpl o-- AdjuntoService
	RecetaServiceImpl o-- AdjuntoService

	HistoriaMedicaService <|.. HistoriaMedicaServiceImpl
	VisitaMedicaService <|.. VisitaMedicaServiceImpl

	GeoUbicacionService <|.. GeoUbicacionServiceImpl

	HistoriaMedicaServiceImpl o-- UsuarioService
	VisitaMedicaServiceImpl o-- HistoriaMedicaService
	PrescripcionServiceImpl o-- VisitaMedicaService

}
@enduml